import Head from 'next/head'
// 4. Use `next-themes` to change the theme
import { useTheme as useNextTheme } from 'next-themes'
import { Switch, useTheme } from '@nextui-org/react'
import { Container, Row, Col } from '@nextui-org/react'
import { useRouter } from 'next/router'

function Home() {

  const router = useRouter()
  const { setTheme } = useNextTheme()
  const { isDark, type } = useTheme()


  return (
    <Container justify='center' css={{ mt: 20 }}>
      <Head>
        <title>Przepisy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row>
        <Col justify='center' align='center' xs={12} md={12} lg={12}>
          <h1 className='title'>Przepisy app</h1>
          <div>
            The current theme is: {type}
            <Switch
              checked={isDark}
              onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
            />

            <>
              Hello
            </>

          </div>
        </Col>
      </Row>
    </Container>
  )
}

export default Home
